// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGhbpJLtTq0WAh15WpBUjGadsowSAxEM',
    appId: '1:447299555397:android:37365b4aabc8bbad',
    messagingSenderId: '447299555397',
    projectId: 'dpss-public-api',
    storageBucket: 'dpss-public-api.appspot.com',
  );

}
